from mrsu/nginx-php:centos
MAINTAINER mrsu <mrsuzhongping@gmail.com>

COPY etc /etc
COPY config /config

ENV WEB_HOME=/home/mrsu/work/learn/php/laravel/faq

VOLUME ${WEB_HOME}

WORKDIR /var/log/nginx/
